package com.eydap.abm;

/**
 * Defines the different types of reports that can be generated by the application.
 * Each report type includes metadata such as the display name,
 * and the specific stored procedure to be called.
 */
public enum ReportType {

    SHOW_COUNTS("Display Last Month Loaded", "ABM_Show_Counts"),

    /**
     * Report for checking data
     */
    CHECK_DATA("Data Check", "ABM_SP_Output_Validation"),

    /**
     * P1
     */
    ABM_SP_EXEC_P1("ABM_SP_Exec_P1", "ABM_SP_Exec_P1"),

    /**
     * P2
     */
    ABM_SP_EXEC_P2("ABM_SP_Exec_P2", "ABM_SP_Exec_P2"),

    /**
     * P3
     */
    ABM_SP_EXEC_P3("ABM_SP_Exec_P3", "ABM_SP_Exec_P3"),

    MASTER_DATA("Master Data Refresh", "ABM_Update_Master_Data"),
    /**
     * Report for Analytical Data (Fact Stats).
     */

    FACT_STATS("Αναλυτικά Δεδομένα (Fact Stats)", "ABM_Process_FactStats"),

    /**
     * Report for Cost (Fact Stats 2).
     */
    FACT_STATS2("Κόστος ΤΦ (Fact Stats2)", "ABM_Process_FactStats2"),

    /**
     * Report for Water (Fact Stats 3).
     */
    FACT_STATS3("Water Report (Fact Stats3)", "ABM_Process_FactStats3");

    private final String displayName;
    private final String procedure;

    /**
     * Constructs a new ReportType enum constant.
     *
     * @param displayName The name to display in the UI.
     * @param procedure   The name of the stored procedure to execute.
     */
    ReportType(String displayName, String procedure) {
        this.displayName = displayName;
        this.procedure = procedure;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getProcedure() {
        return procedure;
    }

    /**
     * Returns the display name of the report, which is used by UI components
     * like ComboBox to show a user-friendly name.
     *
     * @return The display name of the report.
     */
    @Override
    public String toString() {
        return displayName;
    }
}