package com.eydap.abm;

/**
 * Defines the different types of reports that can be generated by the application.
 * Each report type includes metadata such as the display name, server, database,
 * and the specific stored procedure to be called.
 */
public enum ReportType {
    /**
     * Report for Master Data
     */

    MASTER_DATA("Master Data Refresh", "2022SRV", "dss_dev", "update_master_data"),

    /**
     * Report for Analytical Data (Fact Stats).
     */

    FACT_STATS("Αναλυτικά Δεδομένα (Fact Stats)", "2022SRV", "dss_dev", "ABM_Process_factstats"),

    /**
     * Report for Cost (Fact Stats 2).
     */
    FACT_STATS2("Κόστος ΤΦ (Fact Stats2)", "2022SRV", "dss_dev", "ABM_Process_factstats2"),

    /**
     * Report for Water (Fact Stats 3).
     */
    FACT_STATS3("Water Report (Fact Stats3)", "2019SRV\\MSSQLSERVER2019", "EYDAP", "ABM_Process_factstats3");

    private final String displayName;
    private final String server;
    private final String database;
    private final String procedure;

    /**
     * Constructs a new ReportType enum constant.
     *
     * @param displayName The name to display in the UI.
     * @param server      The database server where the procedure is located.
     * @param database    The database name.
     * @param procedure   The name of the stored procedure to execute.
     */
    ReportType(String displayName, String server, String database, String procedure) {
        this.displayName = displayName;
        this.server = server;
        this.database = database;
        this.procedure = procedure;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getServer() {
        return server;
    }

    public String getDatabase() {
        return database;
    }

    public String getProcedure() {
        return procedure;
    }

    /**
     * Returns the display name of the report, which is used by UI components
     * like ComboBox to show a user-friendly name.
     *
     * @return The display name of the report.
     */
    @Override
    public String toString() {
        return displayName;
    }
}
